package AdditionModule;

/**
* AdditionModule/AdditionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdditionModule.idl
* Monday, 29 May, 2023 7:20:36 PM IST
*/

public final class AdditionHolder implements org.omg.CORBA.portable.Streamable
{
  public AdditionModule.Addition value = null;

  public AdditionHolder ()
  {
  }

  public AdditionHolder (AdditionModule.Addition initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdditionModule.AdditionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdditionModule.AdditionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdditionModule.AdditionHelper.type ();
  }

}
