package AdditionModule;


/**
* AdditionModule/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdditionModule.idl
* Monday, 29 May, 2023 7:20:36 PM IST
*/

public interface AdditionOperations 
{
  double add (double num1, double num2);
} // interface AdditionOperations
